#!/bin/bash
usage() {
    cat << USAGE >&2
USAGE:
    $ build-environment.sh [PARAMETERS]
PARAMETERS:
    --build-base-bee                    The base bee image will be built from source code
    --base-bee-commit-hash=string       the source code commit hash of the base bee; Default: HEAD; Dependency: --build-base-bee
    --gen-traffic=boolean               Generate traffic before bee image commit. Default: false
    --gen-traffic-upload-node=string    The traffic will be generated on the node under the given URL. Default: http://locahost:1633; Dependency: --gen-traffic
    --cheques-receiver-node=string      The cheques will be checked on the node under the given URL. Default: http://localhost:11633; Dependency: --gen-traffic
    --cheques-count=number              this amount of cheques is intended to be generated by the traffic gen. Default: 2; Dependency: --gen-traffic
USAGE
    exit 1
}

echoerr() {
     >&2 echo "$@"
}

build_bee() {
    # Clone source code
    BEE_SOURCE_PATH=$MY_PATH/../bee
    if [ -d "$BEE_SOURCE_PATH" ] ; then
        rm -rf "$BEE_SOURCE_PATH"
    fi
    mkdir "$BEE_SOURCE_PATH" && cd "$BEE_SOURCE_PATH" || exit 1
    git init
    git remote add origin https://github.com/ethersphere/bee.git
    git fetch origin --depth=1 "$COMMIT_HASH"
    git reset --hard FETCH_HEAD
    # Build bee and make docker image
    export BEE_VERSION=${COMMIT_HASH::7}-commit
    make binary
    echo "Bee image will be built with version: $BEE_VERSION"
    docker build . -t ethersphere/bee:$BEE_VERSION
    cd "$MY_PATH" || exit 1
    # Set build image tag so that other terminal session can retrieve
    "$MY_PATH/utils/build-image-tag.sh" set "$BEE_VERSION"
}

MY_PATH=$(dirname "$0")
MY_PATH=$( cd "$MY_PATH" && pwd )
COMMIT_HASH=HEAD
BUILD_BASE_BEE=false
GEN_CHEQUES=false

# handle passed options
while [ $# -gt 0 ]
do
    case "$1" in
        --build-base-bee)
        BUILD_BASE_BEE=true
        shift 1
        ;;
        --base-bee-commit-hash=*)
        COMMIT_HASH="${1#*=}"
        shift 1
        ;;
        --gen-cheques)
        GEN_CHEQUES=true
        shift 1
        ;;
        *)
        echoerr "Unknown argument: $1"
        usage
        ;;
    esac
done

if $BUILD_BASE_BEE ; then 
    build_bee
fi
"$MY_PATH/network.sh"
"$MY_PATH/blockchain.sh"
npm run migrate:contracts
npm run supply
if $GEN_CHEQUES ; then
  npm run gen:traffic -- 
fi
"$MY_PATH/blockchain-docker-build.sh"
"$MY_PATH/bee-docker-build.sh"

echo "Successfully build bee environment. Please set BEE_VERSION variable to $BEE_VERSION to run the built environment"
